### PR TITLE
Add microauth-google to the list of available authentication modules …

### PR DESCRIPTION
**Pull request by rapzo**
…for ▲zeit's micro.

### CODE REVIEW

**Comment by dimapaloskin** [comment]
@rapzo do you have plans to transfer your repo into `mircoauth` organization? If no, I will merge it right now, otherwise we need to change repo link :)

**Comment by rapzo** [comment]
I'll move and update the url. Just give me some time and i'll get into it.

Thanks for adding me to the fold. Real nice!

**Comment by rapzo** [comment]
Moved the repo and updated!
Thanks again for letting me be part of this. You da man!

**Comment by dimapaloskin** [comment]
Awesome! :) Thank you!
Merged 😎

**Pull request merged**
